name: Build Buildroot

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  REPO_URL: https://github.com/buildroot/buildroot
  REPO_BRANCH: 2024.02.x
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install -y wget git bc bison flex libssl-dev make libc6-dev libncurses5-dev rsync cpio unzip python3 file
        sudo timedatectl set-timezone "$TZ"

    - name: Clone source code
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH buildroot

    - name: Configure Buildroot
      run: |
        cd buildroot
        make qemu_aarch64_virt_defconfig
        echo 'BR2_TARGET_GENERIC_ISSUE="Welcome to My Own System!"' >> .config

    - name: Compile the firmware
      id: compile
      run: |
        cd buildroot
        echo ">>> Compiling my own system..."
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "::set-output name=status::success"

    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      if: steps.compile.outputs.status == 'success' && !cancelled()
      with:
        name: myown-system
        path: buildroot/output/images
